breweryaz:
  connection_type: database
  description: Sample Brewery Management System Database (hosted on synapse)
  linked_service_name: BreweryPostgres_v1
  name: breweryaz
  parameters:
    additional_properties: sslmode=require
    database: postgres
    database_type: PSQL
    host: dig-brewery-sandbox.postgres.database.azure.com
    password_key: breweryaz__password
    port: 5432
    schema: sppl
    username: postgres
